version: '2'
networks:
  default:
    external:
      name: service_default
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
     - "0:80"
    mem_reservation: 5000k
  admin:
    image: "imma:latest"
    ports:
     - "0:22"
    mem_reservation: 5000k
