#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_ecs="$(ecs -v 2>/dev/null | awk '{print $3}' || true)"
  jq -n --arg ecs "$ver_ecs" '{ecs: $ecs}'
}

version "$@"
