#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_ecs="0.0.1"
  jq -n --arg ecs "$ver_ecs" '{ecs: $ecs}'
}

version "$@"
